/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlkh.view;

import chart.ModelChart;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import qlkh.entity.Storage;

/**
 *
 * @author RAVEN
 */
public class ChartView extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public ChartView() {
        initComponents();
        this.setBackground(new java.awt.Color(95, 148, 212));
        this.setVisible(false);
//        getContentPane().setBackground(new Color(250, 250, 250));
//        chart.addLegend("Income", new Color(245, 189, 135));
//        chart.addLegend("Expense", new Color(135, 189, 245));
//        chart.addLegend("Profit", new Color(189, 135, 245));
//        chart.addLegend("Cost", new Color(139, 229, 222));
//        chart.addData(new ModelChart("January", new double[]{500, 200, 80, 89}));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        chart = new chart.Chart();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDark1 = new swing.tabledark.TableDark();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(95, 148, 212));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 40, 29));

        chart.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        getContentPane().add(chart, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 620, 420));

        tableDark1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kí hiệu", "Tên hàng"
            }
        ));
        jScrollPane2.setViewportView(tableDark1);
        if (tableDark1.getColumnModel().getColumnCount() > 0) {
            tableDark1.getColumnModel().getColumn(0).setPreferredWidth(4);
            tableDark1.getColumnModel().getColumn(1).setPreferredWidth(100);
        }
        tableDark1.fixTable(jScrollPane2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 312, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Biểu đồ số lượng hàng ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 276, 52));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 580));
        jLabel3.setIcon(new ImageIcon("src/main/java/Images/BG.jpg"));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        chart.start();
    }//GEN-LAST:event_formWindowOpened

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChartView().setVisible(true);
            }
        });
    }
    public static String abbreviation(String word) {
    if (!word.trim().contains(" ")) { // Kiểm tra nếu chuỗi không có khoảng trắng thì trả về ký tự đầu tiên của chuỗi
        return word;
    }
    String[] words = word.split(" ");
    StringBuilder abbreviation = new StringBuilder();
    for (String w : words) {
        if (!w.isEmpty()) {
            abbreviation.append(Character.toUpperCase(w.charAt(0)));
        }
    }
    return abbreviation.toString();
}
    public void setChartQuantity(List<Storage> stList){
        
        int size = 18;
        if (stList.size()>10){
            size = size - (stList.size()-10);
        }
        chart.setFont(new java.awt.Font("sansserif", 0, size)); 
        String [] columnNames = new String [] {
            "Kí hiệu", "Tên hàng"};
        chart.addLegend("Số lượng", new Color(200,255,255));
        
        
        for(int i = 0;i<stList.size();i++){
             chart.addData(new ModelChart(abbreviation(stList.get(i).getName()), new double[]{stList.get(i).getQuantity()}));
        }
         Object [][] storage = new Object[stList.size()][2];
         for (int i = 0; i < stList.size(); i++) {
            storage[i][0] = abbreviation(stList.get(i).getName());
            storage[i][1] = stList.get(i).getName();
        }
        tableDark1.setModel(new DefaultTableModel(storage, columnNames));
        if (tableDark1.getColumnModel().getColumnCount() > 0) {
             tableDark1.getColumnModel().getColumn(0).setPreferredWidth(4);
              tableDark1.getColumnModel().getColumn(1).setPreferredWidth(100);
}

        chart.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chart.Chart chart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private swing.tabledark.TableDark tableDark1;
    // End of variables declaration//GEN-END:variables
}
