/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlkh.view;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import qlkh.entity.Storage;
import swing.scrollbar.ScrollBarCustom;

/**
 *
 * @author Admin
 */
public class EditView extends javax.swing.JFrame {

    /**
     * Creates new form EditView1
     */
    public EditView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cancelButton = new swing.button.ButtonGradient();
        clearButton = new swing.button.ButtonGradient();
        confirmButton = new swing.button.ButtonGradient();
        priceField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        unitField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nameField = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        NameOfEdit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon("src/main/java/Images/AppIcon.jpg").getImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 40, 29));

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        cancelButton.setText("Hủy");
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 90, 50));

        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        clearButton.setText("Clear");
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 90, 50));

        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        confirmButton.setText("Xác nhận");
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 90, 50));

        priceField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        priceField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 230, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 118, 211));
        jLabel9.setText("Giá");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 70, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 118, 211));
        jLabel8.setText("Số lượng");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, 30));

        quantityField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        quantityField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(quantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 100, 30));

        unitField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        unitField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(unitField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 118, 211));
        jLabel7.setText("Đơn vị");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 70, 30));

        jScrollPane1.setBorder(null);

        nameField.setColumns(20);
        nameField.setRows(5);
        nameField.setBorder(null);
        nameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(nameField);
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
        jScrollPane1.setHorizontalScrollBar(new ScrollBarCustom());

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 310, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 118, 211));
        jLabel6.setText("Tên hàng");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 70, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 118, 211));
        jLabel5.setText("Mã hàng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 30));

        idField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        idField.setEnabled(false);
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, 30));

        NameOfEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NameOfEdit.setForeground(new java.awt.Color(25, 118, 211));
        NameOfEdit.setText("CHỈNH SỬA HÀNG ");
        getContentPane().add(NameOfEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 280, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("src/main/java/Images/BG.jpg"));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditView().setVisible(true);
            }
        });
    }
public void setIdFieldText(String s){
       this.idField.setText(s);
    }
    public void setNameFieldText(String s){
       this.nameField.setText(s);
    }
    public void setUnitFieldText(String s){
       this.unitField.setText(s);
    }
    public void setQuantityFieldText(String s){
       this.quantityField.setText(s);
    }
    public void setPriceFieldText(String s){
       this.priceField.setText(s);
    }
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    public boolean validateName() {
        String name = nameField.getText();
        if (name == null || "".equals(name.trim())) {
            nameField.requestFocus();
            showMessage("Tên hàng không được trống.");
            return false;
        }
        return true;
    }
    
    public boolean validateUnit() {
        String unit = unitField.getText();
        if (unit == null || "".equals(unit.trim())) {
            unitField.requestFocus();
            showMessage("Đơn vị không được trống.");
            return false;
        }
        return true;
    }
    
    
    public boolean validateQuantity() {
        try {
            int Qtt = Integer.parseInt(quantityField.getText().trim());
            if (Qtt < 0) {
                quantityField.requestFocus();
                showMessage("Số lương không hợp lệ! Số lượng phải lớn hơn 0.");
                return false;
            }
        } catch (Exception e) {
            quantityField.requestFocus();
            showMessage("Số lượng không hợp lệ!");
            return false;
        }
        return true;
    }
    
    public boolean validatePrice() {
        try {
            int price = Integer.parseInt(priceField.getText().trim());
            if (price < 0) {
                priceField.requestFocus();
                showMessage("Giá không hợp lệ! Giá phải lớn hơn 0.");
                return false;
            }
        } catch (Exception e) {
            priceField.requestFocus();
            showMessage("Gía không hợp lệ!");
            return false;
        }
        return true;
    }
     public Storage getStorageInfo() {
        // validate student
        if (!validateName() || !validateUnit() || !validatePrice() || !validateQuantity()) {
            return null;
        }
        try {
            Storage st = new Storage();
            if (idField.getText() != null && !"".equals(idField.getText())) {
                st.setId(Integer.parseInt(idField.getText()));
            }
            st.setName(nameField.getText().trim());
            st.setQuantity(Integer.parseInt(quantityField.getText().trim()));
            st.setUnit(unitField.getText().trim());
            st.setPrice(Integer.parseInt(priceField.getText().trim()));
            return st;
        } catch (Exception e) {
            showMessage(e.getMessage());
        }
        return null;
    }
     public void addClearListener(ActionListener listener) {
        clearButton.addActionListener(listener);
    }
     public void addConfirmListener(ActionListener listener) {
        confirmButton.addActionListener(listener);
    }
     public void addCancelListener(ActionListener listener) {
        cancelButton.addActionListener(listener);
    }
     public void callAdd(){
         NameOfEdit.setText("     THÊM HÀNG");
     }
     public void callEdit(){
         NameOfEdit.setText("CHỈNH SỬA HÀNG");
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameOfEdit;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea nameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTextField unitField;
    // End of variables declaration//GEN-END:variables
}
